version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
           POSTGRES_HOST: ${POSTGRES_HOST}
           POSTGRES_DB: ${POSTGRES_DB}
           POSTGRES_USER: ${POSTGRES_USER}
           POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  django:
    container_name: django
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - logstash
    networks:
      - backend
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PIPELINE: local
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: barbayjuliette95@gmail.com
      #ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      #ELASTICSEARCH_URL=http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html 
      - ./logs:/var/log/nginx
      - ./pong/staticfiles:/app/pong/staticfiles
      - ./pong/media:/app/pong/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - kibana
    networks:
      - backend

  elasticsearch:
    container_name: elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - path.repo=/usr/share/elasticsearch/backup
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/init/setup.sh:/setup.sh
      - ./backup:/usr/share/elasticsearch/backup
    ports:
      - "9200:9200"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:$ELASTIC_PASSWORD", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
  setup:
    container_name: setup
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./elasticsearch/init/setup.sh:/setup.sh
      #- ./backup:/usr/share/elasticsearch/backup
    entrypoint: ["/bin/sh", "/setup.sh"]
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - backend
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_URL=http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend
  logstash:
    container_name: logstash
    restart: always
    image: docker.elastic.co/logstash/logstash:7.17.0
    ports:
      - "5044:5044"
    volumes:
      #- ./logstash/config:/usr/share/logstash/config
      #- ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/share/logstash/log/nginx_logs
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - backend

volumes:
  postgres_data:
  esdata:


networks:
  backend:
    driver: bridge
