version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
           POSTGRES_HOST: ${POSTGRES_HOST}
           POSTGRES_DB: ${POSTGRES_DB}
           POSTGRES_USER: ${POSTGRES_USER}
           POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  django:
    container_name: django
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./logs:/var/log
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - logstash
    networks:
      - backend
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PIPELINE: local
      DJANGO_SUPERUSER_USERNAME: ${SUPER_USER}
      DJANGO_SUPERUSER_PASSWORD: ${SUPER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${SUPER_EMAIL}
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html 
      - ./logs:/var/log/nginx
      - ./pong/staticfiles:/app/pong/staticfiles
      - ./pong/media:/app/pong/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - backend

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - path.repo=/usr/share/elasticsearch/backup
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/init/setup.sh:/setup.sh
      - ./backup:/usr/share/elasticsearch/backup
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
    # ports:
    #   - "9200:9200"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:$ELASTIC_PASSWORD", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 10
  setup:
    container_name: setup
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - ./elasticsearch/init/setup.sh:/setup.sh
    entrypoint: ["/bin/sh", "/setup.sh"]
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - backend
  kibana:
    container_name: kibana
    build:
      context: ./kibana
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - KIBANA_ENCRYPTION_KEY=${KIBANA_ENCRYPTION_KEY}
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
        test: ["CMD-SHELL", "until curl -f -k -u elastic:$ELASTIC_PASSWORD https://localhost:5601/api/status | grep -q 'green'; do sleep 5; done"]
        interval: 30s
        timeout: 10s
        retries: 10

  logstash:
    container_name: logstash
    restart: always
    image: docker.elastic.co/logstash/logstash:7.17.0
    # ports:
    #   - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/share/logstash/log/nginx_logs
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch
    environment:
       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - backend

volumes:
  postgres_data:
  esdata:


networks:
  backend:
    driver: bridge
