# Generated by Django 5.1 on 2024-09-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'Game Results'},
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name_plural': 'Stats'},
        ),
    ]
