# Generated by Django 5.1 on 2024-10-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='opponent_username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
