POST http://127.0.0.1:8000/signup Content-Type: application/json

{ "username": "anna", "password": "Pass1234!", "email": "anna@mail.com" }

###

POST http://127.0.0.1:8000/login Content-Type: application/json

{ "username": "anna", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token Content-Type: application/json Authorization: token xxx


curl -H "Authorization: Token 5644fccd75046dd83d01116deffdf2c4370f7aac" -H "Content-Type: application/json" http://127.0.0.1:8000/test_token
